yongbeomkwak/SwiftUI-Study

SwiftUI/Beginner/Hannah/Text/README.md
=> : pencil2 : :: 부트캠프 Text 리드미 추가

SwiftUI/Beginner/Hannah/Shape/README.md
=> :page_facing_up: :: 부트캠프 #3 Shape 리드미 추가

SwiftUI/Beginner/Snack/Backgrounds, Overlays/README.md, SwiftUI/Beginner/Snack/Color/README.md, SwiftUI/Beginner/Snack/Frame/README.md, SwiftUI/Beginner/Snack/Gradients/README.md, SwiftUI/Beginner/Snack/Icons/README.md, SwiftUI/Beginner/Snack/Padding, Spacer/README.md, SwiftUI/Beginner/Snack/Shape/README.md, SwiftUI/Beginner/Snack/Stack/README.md, SwiftUI/Beginner/Snack/Text/README.md
Snack SwiftUI Readme 정리
- Text
- Color
- Gradients
- Icons
- Shape
- Frame
- Backgrounds, Overlays
- Stack
- Padding, Spacer
=> Snack SwiftUI Readme 정리

SwiftUI/Beginner/Hannah/#16 Grids/README.md, SwiftUI/Beginner/Hannah/#17 Ignore Safe Area/README.md, SwiftUI/Beginner/Hannah/#18 Buttons/README.md, SwiftUI/Beginner/Hannah/#28 Sheets/README.md
16. Grids 리드미 작성
17. Ignore Safe Area 리드미 작성
18. Buttons 리드미 작성
=> 해나 리드미 업로드

SwiftUI/Beginner/Snack/ActionSheet/README.md, SwiftUI/Beginner/Snack/Alert/README.md, SwiftUI/Beginner/Snack/List/README.md, SwiftUI/Beginner/Snack/OnAppear, OnDisappear/README.md
=> :clap: :: Snack Readme

SwiftUI/Beginner/Snack/If Let, Guard Let/README.md, SwiftUI/Beginner/Snack/OnTapGesture/README.md, SwiftUI/Beginner/Snack/Transition/README.md
- If Let, Guard Let
- OnTapGesture
- Transition
=> :clap: :: Snack Readme 추가

SwiftUI/Summary/If Let, Guard Let/README.md, SwiftUI/Summary/OnAppear, OnDisappear/README.md, SwiftUI/Summary/OnTapGesture/README.md
- #46 OnAppear, OnDisAppear Summary 추가
- #47 If Let, Guard Let Summary 추가
- #48 OnTapGesture Summary 추가
=> :clap: :: #46 #47 #48 Summary 추가

SwiftUI/Summary/@EnvironmentObject/README.md, SwiftUI/Summary/@ObservableObject & @StateObject/README.md, SwiftUI/Summary/Custom Models/README.md
49, 50, 51 Summary 리드미 작성 완료
- :page_facing_up: :: #49 Custom Models Summary 리드미 추가
- :page_facing_up: :: #50 @ObservableObject & @StateObject Summary 리드미 추가
- :page_facing_up: :: #51 @EnvironmentObject Summary 리드미 추가
=> 해나 49, 50, 51 Summary 리드미 작성 PR

SwiftUI/Beginner/Snack/@AppStorage/README.md, SwiftUI/Beginner/Snack/NavigationStack/README.md, SwiftUI/Summary/@AppStorage/README.md, SwiftUI/Summary/NavigationStack/README.md
- #52 @AppStorage 추가
- NavigationStack 추가
=> :clap: :: #52 @AppStorage, NavigationStack 추가

SwiftUI/Beginner/Koby/#57_Button styles and control sizes/README.md, SwiftUI/Beginner/Koby/#58_List Swipe Actions/README.md, SwiftUI/Beginner/Koby/#59_Badges/README.md
- #57 Button styles and control sizes 리드미 작성
- #58 List Swipe Actions 리드미 작성
- #59 Badges  리드미 작성
=> :clap: :: Koby Readme

SwiftUI/Summary/AsyncImage/README.md, SwiftUI/Summary/Background Materials/README.md, SwiftUI/Summary/TextSelection/README.md
David Goggins #54 #55 #56 리드미 작성
#54 #55 #56 리드미 작성
=> David goggins branch

SwiftUI/Summary/Badges/README.md, SwiftUI/Summary/Button styles/README.md, SwiftUI/Summary/List Swipe Actions/README.md
=> :pencil2: :: Koby 리드미 서머리 추가 

SwiftUI/Summary/@EnvironmentObject/README.md, SwiftUI/Summary/Custom Models/README.md
잘못된 Summary 수정
- 49_Custom Models 리드미 코드 정렬 수정
- 51_@EnvironmentObject 리드미 코드 정렬 수정
=> 해나 Summary 수정

SwiftUI/Summary/High Order Function/README.md, SwiftUI/Summary/TodoList/TodoList/Views/NoItemsView.swift
=> :clap: 고차함수

SwiftUI/Summary/Multi-threading/README.md
=> :clap: 메인스레드

SwiftUI/Intermediate/Hannah/#12 Hashable Protocol/README.md, SwiftUI/Summary/Hashable Protocol/README.md
12_Hashable Protocol 리드미 추가
:page_facing_up: :: #12 Hashable Protocol 리드미 추가
:hammer_and_wrench: :: #12 리드미 제목 수정
:pencil2: :: #12 Hashable Protocol Summary 리드미 추가
=> :page_facing_up: :: #12 Hashable Protocol 리드미 추가

SwiftUI/Intermediate/goggins/#11 Local Notification/README.md, SwiftUI/Summary/Local Notification/README.md
=> :page_facing_up: :: #11Local Notification

SwiftUI/Summary/Codable/README.md
=> :clap: 코더블

SwiftUI/Intermediate/Hannah/#19 Typealias/README.md
19_Typealias 리드미 추가
:page_facing_up: :: #19 Typealias 리드미 추가
=> :page_facing_up: :: #19 Typealias 리드미 추가

SwiftUI/Summary/Typealias/README.md
19_Typealias summary에 리드미 추가
:pencil2: :: #19 Typealias Summary 리드미 추가
=> 해나 서머리 리드미 추가 PR

SwiftUI/Intermediate/goggins/#18 WeakSelf/README.md
#18 WeakSelf 리드미 추가
WeakSelf 리드미 추가
=> :tada: :: #18 WeakSelf 리드미 추가

SwiftUI/Summary/Weak self/README.md
=> :clap: Weak Self

SwiftUI/Intermediate/Snack/@escaping/README.md, SwiftUI/Summary/@escaping/README.md
=> :clap: :: @escaping Readme

SwiftUI/Intermediate/Hannah/#24 Timer & onReceive/README.md, SwiftUI/Summary/Timer & onReceive/README.md
Timer & onReceive 리드미 추가
:page_facing_up: :: #24 Timer & onReceive 리드미 추가
=> 해나 리드미 추가 PR

SwiftUI/Intermediate/Snack/Publishers, Subscribers/README.md, SwiftUI/Summary/@escaping/README.md, SwiftUI/Summary/Publishers, Subscribers/README.md
- Publishers, Subscribers Reame 추가
=> :clap: :: Publishers, Subscribers Reame 추가

SwiftUI/Intermediate/goggins/#22 URLSession and escaping closures/README.md, SwiftUI/Intermediate/goggins/#23 Combine/README.md
#22 URLSession and escaping closures
#23 Combine
#22 URLSession and escaping closures 리드미 작성
#23 Combine 리드미 작성
=> David goggins

SwiftUI/Beginner/Koby/#27_Transition_추가/README.md, SwiftUI/Intermediate/Koby/#1_ViewModifier/README.md, SwiftUI/Summary/Transition/README.md, SwiftUI/Summary/ViewModifier/README.md
- trasition에서 .animation 관련 update 된 내용 보완 및 gif 추가
- 베지어 타이밍 커브 애니메이션 내용 추가
- viewmodifier 리드미
=> :clap: :: 코비 리드미

SwiftUI/Intermediate/goggins/#10 PreferenceKey/README.md, SwiftUI/Summary/PreferenceKey/README.md
:tada: #10 PreferenceKey 리드미 추가
#10 PreferenceKey 리드미 추가
#10 PreferenceKey 리드미 추가
=> :tada: #10 PreferenceKey 리드미 추가

SwiftUI/Intermediate/Hannah/#9 @ViewBuilder/README.md, SwiftUI/Summary/@ViewBuilder/README.md
@ViewBuilder 리드미 추가
- :page_facing_up: :: @ViewBuilder Intermediate 폴더에 리드미 추가
=> :page_facing_up: :: @ViewBuilder 리드미 추가

SwiftUI/Intermediate/Koby/#8_Generics/README.md, SwiftUI/Summary/Generics/README.md
=> :clap: :: 코비 Generic 리드미 추가
